# --- Konstanta ---
TILE_SIZE = 64
MAP_WIDTH = 20
MAP_HEIGHT = 12
SCREEN_WIDTH = MAP_WIDTH * TILE_SIZE
SCREEN_HEIGHT = MAP_HEIGHT * TILE_SIZE

WALK_SPEED = 1.5
RUN_SPEED = 4
CROUCH_SPEED = 0.8
GUARD_SPEED = 1.0
SCALE = 2

# Ukuran ruangan 2 yang lebih besar
ROOM2_WIDTH = 30
ROOM2_HEIGHT = 19
